spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/sky_take_out?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2006hzJ.
  servlet:
    encoding:
      charset: UTF-8
      multipart:
        enabled: true
        max-file-size: 2MB
        max-request-size: 2MB
logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info
  pattern:
    dateformat: HH:mm:ss

mybatis-plus:
  type-aliases-package: zhijianhu.demo01.pojo
  global-config:
    db-config:
      id-type: auto
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  pagination:
    enabled: true
sky:
  jwt:
    admin-secret-key: aHV6aGlqaWFu
    admin-ttl: 7200000
    admin-token-name: token
  alioss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    bucket-name: huzhijian-springboot-csse
    region: cn-guangzhou


