sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 2006hzJ.
  redis:
     port: 6379
     password: hzj1102.
     host: localhost
     database: 0
